export const images = [
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Custom Suits", title: "Custom Suits" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Custom Shirts", title: "Custom Shirts" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Blazers", title: "Blazers" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Wedding", title: "Wedding" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Polo shirts", title: "Polo shirts" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Tux", title: "Tux" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Suits", title: "Suits" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Shirts", title: "Shirts" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Trousers", title: "Trousers" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Jackets", title: "Jackets" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Accessories", title: "Accessories" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Casual Wear", title: "Casual Wear" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Formal Wear", title: "Formal Wear" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Custom Tailoring", title: "Custom Tailoring" },
  { src: "/suit.png", hoverSrc: "/suit-hover.jpg", alt: "Bespoke Suits", title: "Bespoke Suits" },
];